### ISSUE TITLE
no card backs on TTS 

### ISSUE THREAD

**Issue by jawkneeb123** [fafranco82/swdestinydb#103]
when I D/L the .json files for TTS ,for the decks , when loaded into the game there is no card back on the cards ,  URL not found 
![20170301081339_1](https://cloud.githubusercontent.com/assets/24786223/23459566/4b0a083c-fe57-11e6-8098-b4f2aaa9d2fd.jpg)

**Comment by fafranco82** [comment]
Hi,

I've just checked the Back URL and it's right... It is http://cloud-3.steamusercontent.com/ugc/102850418890247821/C495C2DA41D081A5CD513AC62BE8F69775DC5ADB/

But this URL has changed a month ago. The .json file you used in TTS was recently downloaded?

**Comment by jawkneeb123** [comment]
yes I download it tonight ,  http://swdestinydb.com/decklist/view/7740/bringmesolo-infamousskum-1.0

 its 4 days old ,

**Comment by tapwatr** [comment]
I just wanna pop in and say i had same issue last night, first time i loaded deck it didn't load back, 2nd time it did but was much brighter than current card backs, so I went in to update the card backs manually. made a deck today and seems to have right card back now so idk what happened.

**Comment by DDoubleVVision** [comment]
Same issue here.  This is the address that is created for the cardback ("BackURL") when I download to TableTopSimulator json file: http://cloud-3.steamusercontent.com/ugc/263845944692793410/D285F2B6F28F272FAAD1BFA25D6DD12660C9972E/

However for the first card in my deck it uses the correct URL posted by fafranco82

**Comment by fafranco82** [comment]
Already fixed with 96e587f17d8fdd91d259a700d1d3048388e7908e :)
