### ISSUE TITLE
Missing SoR cards

### ISSUE THREAD

**Issue by jgoldshlag** [fafranco82/swdestinydb#106]
Now that people like me got cards from the SoR preview events, we want to add our cards and build decks. I know everything hasn't been officially spoiled, but the list at https://pastebin.com/UJb1DZ2x is pretty close

**Comment by fafranco82** [comment]
Thank you. But I want to keep the cards with official texts because then it's a lot of work to check what was unofficialy translated and at the end is double work... Anyway, a lot of people are sending me official texts from cards pulled out from their pre-release booster :)

**Comment by jgoldshlag** [comment]
You are still missing a couple cards. From my personal pulls:

Aurra Sing (unique)
Deadly Shot

10 health. 14/18 cost
1 Rd/2 Rd/2 Rd/1 Disrupt/1 Resource/Blank

Character
Before you resolve this die, you may discard a card from your hand to increase its value by 1
"Well, what do we have here?"
SoR number 18/Villian/Yellow/Rare

And:
One-Quarter Portion
1 cost Event
Remove and opponent's die. Then that opponent gains 1 resource
Villian/Yellow/common/SoR number 85

And:
Sabotage
1 cost event
Discard cards from your hand equal to the cost of a support in play to discard that support.
Neutral/Yellow/uncommon/SoR number 147

And:
Moisture Farm
Tatooine
Battlefield
Claim - Gain 1 resource
Neutral/Uncommon/SoR 156

**Comment by jgoldshlag** [comment]
Also, doubt is not blue, it is gray

**Comment by jgoldshlag** [comment]
another correction: Tie pilot is 7 health, not 12

**Comment by fafranco82** [comment]
All added and fixed. Thank so much!
