### ISSUE TITLE
minor spelling corrections / card images

### ISSUE THREAD

**Issue by Wigs36** [fafranco82/swdestinydb#107]
Hi,

I just wanted to contribute with some spelling corrections to cards in the Spirit of Rebellion collection:

- Command Shuttle - instead of Command'o'.....
- Guavian Enforcer - instead of .....Enfo'n'cer
- We Have Them Now - instead of W'h'e.....

Also, are you accepting image contributions to cards that are missing? I am currently scanning the cards I pulled today from pre-release. What format would be better?

Thanks.

Best regards,

Wagner

**Comment by fafranco82** [comment]
Fixed! Thank you!
