### ISSUE TITLE
Can't publish SoR decks

### ISSUE THREAD

**Issue by jgoldshlag** [fafranco82/swdestinydb#108]
I'm getting an error trying to publish a deck with SoR cards in it:
"You cannot publish this deck yet, because it has unreleased cards."

Probably no good reason to restrict things this way

**Comment by fafranco82** [comment]
Hello,

The decklist section is intended to share and show legal decklist for tournaments, so you can't publish decklists witn unreleased cards. Anyway, you can share your decks with your friends activating this option in your account settings, and sharing the URL of your your deck.

Regards.
