### ISSUE TITLE
[Mobile App] Image url API change

### ISSUE THREAD

**Issue by dogo** [fafranco82/swdestinydb#110]
@fafranco82 

Since commit 6d30cfad716e4377272fff3b8b2740bbd98638c3, my app is not able to load any image, the property imageURL its a relative path and I don't expect this. It will be final this change? I will need to update my code and all my older builds will fail to load the images

New JSON reponse:
"imagesrc":"/bundles/cards/en/01/01001.jpg"

Old JSON response:
"imagesrc":"http://s3.amazonaws.com/swdestinydb-prod/01001.jpg"

**Comment by fafranco82** [comment]
I've just updated the code to return absolute URIs ;)

**Comment by dogo** [comment]
Thanks, just waiting the server update  😁

**Comment by fafranco82** [comment]
The server is updated, just refresh cache ;)

**Comment by dogo** [comment]
Indeed!

**Comment by harkonen187** [comment]
How do I clear the cache on iOS?

**Comment by dogo** [comment]
Humm something is weird here, all the SoR available images are loading fine, but the AWK aren't. I will investigate why the cache is not invalidating, @fafranco82 do you change anything related to the cache expiration ?

**Comment by fafranco82** [comment]
Nope, all the headers are the same.

**Comment by dogo** [comment]
Okayy! Thanks for your support 😋
