### ISSUE TITLE
Something is horribly wrong error message

### ISSUE THREAD

**Issue by harkonen187** [fafranco82/swdestinydb#111]
I downloaded SWDTrades for iOS a few days ago and this morning I keep getting the error message: Something is horribly wrong! Tap here to check if swdestinydb.com is online 

As far as I can tell your site is ok. Is this a known bug? I have deleted and reinstalled the app and the problem persists. 

Help!

**Comment by fafranco82** [comment]
@dogo this is for the relative url issue?

**Comment by harkonen187** [comment]
I have cleared my cache as described in the other thread and the problem persists.

**Comment by dogo** [comment]
@fafranco82 I don't think so. It's related to network issue

@harkonen187 this message appears when the http://swdestinydb.com is offline for some reason, I'm using the app right know and seems fine. Could you please provide me more information.

Thanks

**Comment by harkonen187** [comment]
Weird. I uninstalled and reinstalled again and it's working now. How bizzare!

**Comment by dogo** [comment]
hahaha yep! but I'm glad for you @harkonen187

**Comment by fafranco82** [comment]
I close this then.
