### ISSUE TITLE
Decklist Search by Card Returning "Undefined" Values

### ISSUE THREAD

**Issue by howdypertner** [fafranco82/swdestinydb#112]
When you enter card names into the card field in the decklist search, you get 'undefined' as a return value. The actual name of the card is not brought up and you can't return specific decks related to the cards you're searching for.

**Comment by fafranco82** [comment]
Fixed with f97094214796e9848ddf947cc1dd7925db5009ac

**Comment by fafranco82** [comment]
(but maybe you can't see changes until cache refreshes)
