### ISSUE TITLE
DB Tags

### ISSUE THREAD

**Issue by dtennant6** [fafranco82/swdestinydb#116]
1.  Quadjumper (Spirit of Rebellion 58) is a Legendary but is tagged as Rare.

![image](https://cloud.githubusercontent.com/assets/27737665/25146118/c8ffb548-2440-11e7-95cd-e528208642cf.png)

2.  Decisive Blow (Spirit of Rebellion127) is a Common but is tagged as Uncommon.

![image](https://cloud.githubusercontent.com/assets/27737665/25146071/ac4f43b4-2440-11e7-8ce3-b666f649eb63.png)

Thank you!

**Comment by fafranco82** [comment]
Fixed!

Thanks! :)
