### ISSUE TITLE
"my collection" is erased/gone??

### ISSUE THREAD

**Issue by Brakus71** [fafranco82/swdestinydb#123]
Hi...

just added all my cards to this db and was happy about the overall good looking and the options around here. but now, ive got a new display and wanted to add my new cards, but when logged in, no more collection available? all gone??

what went wrong? i did save all several times, @last loging!!!

**Comment by fafranco82** [comment]
I've just checked it in DB and your collection is still there... (if your username it's the same as in github).

Can you add an screenshot of your empty collection??

**Comment by Brakus71** [comment]
Thx. so much for the fast response!

 

Ive just checked back and yes, now it’s there!!!!! Great 😊 …..but weird….wondering what went wrong before……is there an option to save the list to my hdd?

 

Verspielte Grüße,

 

Pascal von Engelbrechten

 <http://www.heimspiele.info/HP> http://www.heimspiele.info/HP 

 <http://www.heimspiele.info/PC> http://www.heimspiele.info/PC

 <https://www.facebook.com/Heimspieleinfo/?fref=ts> https://www.facebook.com/Heimspieleinfo/?fref=ts

 

Von: Francisco Franco Eslava [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Mai 2017 14:32
An: fafranco82/swdestinydb <swdestinydb@noreply.github.com>
Cc: Brakus71 <info@heimspiele.info>; Author <author@noreply.github.com>
Betreff: Re: [fafranco82/swdestinydb] "my collection" is erased/gone?? (#123)

 

I've just checked it in DB and your collection is still there... (if your username it's the same as in github).

Can you add an screenshot of your empty collection??

**Comment by fafranco82** [comment]
Not yet, but I'm working on it right now (but in my spare time...). I hope it's done before next month.

**Comment by Brakus71** [comment]
Ok, cool^^

 

 

Verspielte Grüße,

 

Pascal von Engelbrechten

 <http://www.heimspiele.info/HP> http://www.heimspiele.info/HP 

 <http://www.heimspiele.info/PC> http://www.heimspiele.info/PC

 <https://www.facebook.com/Heimspieleinfo/?fref=ts> https://www.facebook.com/Heimspieleinfo/?fref=ts

 

Von: Francisco Franco Eslava [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Mai 2017 15:56
An: fafranco82/swdestinydb <swdestinydb@noreply.github.com>
Cc: Brakus71 <info@heimspiele.info>; Author <author@noreply.github.com>
Betreff: Re: [fafranco82/swdestinydb] "my collection" is erased/gone?? (#123)

 

Not yet, but I'm working on it right now (but in my spare time...). I hope it's done before next month.

**Comment by Brakus71** [comment]
Hi….

 

Same problem again!

Cant see my collection….

 

See attached screenshot.

 

Just refreshed the browser-tab / logged-in.

 

Dunno whats up……

 

 

Verspielte Grüße,

 

Pascal von Engelbrechten

 <http://www.heimspiele.info/HP> http://www.heimspiele.info/HP 

 <http://www.heimspiele.info/PC> http://www.heimspiele.info/PC

 <https://www.facebook.com/Heimspieleinfo/?fref=ts> https://www.facebook.com/Heimspieleinfo/?fref=ts

 

Von: Francisco Franco Eslava [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Mai 2017 15:56
An: fafranco82/swdestinydb <swdestinydb@noreply.github.com>
Cc: Brakus71 <info@heimspiele.info>; Author <author@noreply.github.com>
Betreff: Re: [fafranco82/swdestinydb] "my collection" is erased/gone?? (#123)

 

Closed #123 <https://github.com/fafranco82/swdestinydb/issues/123> .

**Comment by Brakus71** [comment]
Im using Google Chrome though…….just checked with IE and the db was found, weird…….

 

------

 

Hi….

 

Same problem again!

Cant see my collection….

 

See attached screenshot.

 

Just refreshed the browser-tab / logged-in.

 

Dunno whats up……

 

 

Verspielte Grüße,

 

Pascal von Engelbrechten

 <http://www.heimspiele.info/HP> http://www.heimspiele.info/HP 

 <http://www.heimspiele.info/PC> http://www.heimspiele.info/PC

 <https://www.facebook.com/Heimspieleinfo/?fref=ts> https://www.facebook.com/Heimspieleinfo/?fref=ts

 

 

Von: Francisco Franco Eslava [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Mai 2017 15:56
An: fafranco82/swdestinydb <swdestinydb@noreply.github.com>
Cc: Brakus71 <info@heimspiele.info>; Author <author@noreply.github.com>
Betreff: Re: [fafranco82/swdestinydb] "my collection" is erased/gone?? (#123)

 

Closed #123 <https://github.com/fafranco82/swdestinydb/issues/123> .
