### ISSUE TITLE
Export Deck Problem

### ISSUE THREAD

**Issue by villagiuseppe** [fafranco82/swdestinydb#128]
In the file json exported from my deck is missing the card id of chirrut imwe (2234)

**Comment by w1nterl0ng** [comment]
I did the code of the original export for Awakenings.  Has someone made updates for SoR?  If not, I cannot image any of those cards working correctly.

**Comment by jmcnett010** [comment]
Has this been fixed? I attempted to replicate this, but chirrut showed up in my exports.

Do you have a link to the deck?

**Comment by villagiuseppe** [comment]
Here is the link of my deck http://swdestinydb.com/deck/view/237797
and the exported file.

[baze-chirrut.json.txt](https://github.com/fafranco82/swdestinydb/files/1067559/baze-chirrut.json.txt)

**Comment by w1nterl0ng** [comment]
without digging into anything, the first thing I noticed is that the card for "Chirrut" does not have a `ttscardid` in the json-data / sor.json file. `https://github.com/fafranco82/swdestinydb-json-data/blob/master/set/SoR.json`
I am not sure who created that, and if it still works the way it did before.  But if you edit your json.txt file search for `Chirrut`  look for the line #154 it says `"CardID":`
it is currently blank, edit it to show:
```"CardID": 2234```
Let me know if that works.  If it does, maybe we could sweep through that JSON DB file and make sure there are not any other blanks and then update it.

**Comment by villagiuseppe** [comment]
Thanks, I had already corrected the file as indicated by you. I opened the issue to report the export error.

A similar error happens with Darth Vader (SOR) card.
In the .json file you need to edit the description "Darth Vader" in "SoR Darth Vader"
Otherwise the TTS will load Darth Vader (AWK) dice.

**Comment by w1nterl0ng** [comment]
Thanks, I am going to fork the data and submit a merge request. wonder how many other issues there are, I hate play whack-a-mole with this.

**Comment by w1nterl0ng** [comment]
I have posted a pull request for the Chirrut issue, not sure how long it will take the author to pick it up and then get is into the live site.

**Comment by w1nterl0ng** [comment]
The first issue (missing id for Chirrut) has been merged by FaFranco, not sure when the data will get populated.  I will update here when it does, so that we can close this ticket.
The second issue, "Darth Vader" Dice may require a coding change, I am not sure when I will have time to look into it, but maybe someone else can.

**Comment by w1nterl0ng** [comment]
This has been merged, and I have tested it.  All looks good.
@villagiuseppe please mark this issue as resolved.
