### ISSUE TITLE
Can't Log in

### ISSUE THREAD

**Issue by bhill0113** [fafranco82/swdestinydb#134]
I am able to log into the site because i have not received a verification email.  I have clicked on the resend the email option several times and have still have not received the email.  I have been trying now for 4 days to gain access to the site.  I enjoy the app on the iphone and wanted to extend the experience to the website.

**Comment by fafranco82** [comment]
What is your registered username?

**Comment by bhill0113** [comment]
Bhill0113

- Bill

**Comment by fafranco82** [comment]
activated! Have fun!

**Comment by bhill0113** [comment]
Thank you. Is there a way to link my iPhone app to the website?  I already catalogued all of my cards on the app. 

- Bill
