### ISSUE TITLE
My Collection: Option to Exclude Unowned Cards

### ISSUE THREAD

**Issue by zliniguez** [fafranco82/swdestinydb#14]
## Summary
When viewing "My Collection" it would be helpful to include an option to not display unowned cards.
## Expected Outcome
When "Show Owned Cards" only option is selected, "My Collection" list only displays items with an "owned" value of 1 or more.

_This would be helpful for quickly displaying what one owns._

**Comment by fafranco82** [comment]
Done :)

**Comment by zliniguez** [comment]
Awesome. Thank you!!! This is especially helpful during this launch party weekend for trading.
