### ISSUE TITLE
Couple missing EaW cards

### ISSUE THREAD

**Issue by jgoldshlag** [fafranco82/swdestinydb#144]
Couple of cards missing from EaW:

Servant of the dark side (#9)
https://cdn.discordapp.com/attachments/333945830434406422/354283102048223233/IMG_20170904_081005.jpg

Yoda's Quarters (#105)
https://cdn.discordapp.com/attachments/333945830434406422/354283198215094303/IMG_20170904_080829.jpg

**Comment by fafranco82** [comment]
Thank you so much!
