### ISSUE TITLE
More missing EaW cards

### ISSUE THREAD

**Issue by jgoldshlag** [fafranco82/swdestinydb#145]
Gamorean Guard: (19)
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21231961_10101010837141379_3342497890911362445_n.jpg?oh=684c9442c6707b82d9b15c13faaf6685&oe=5A567727

Energy Slingshot: (43), Deadly (86), Rearguard (92), Mandalorean Armor (145)
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21314579_1509403639139393_4753902169406861288_n.jpg?oh=ef461df8514dfbd2e2863b339b7597af&oe=5A52829B

Extortion (54), Pilfered Goods (83), Tech Team (127):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21231215_1510146215731802_6289271868457700760_n.jpg?oh=af8f6aff1af8cb081ff8d156b700dc7a&oe=5A1294CC

As You Command (70), Dangerous Mission (146):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21192585_691809407680623_7443752770659867057_n.jpg?oh=3be35ff634c3e7f59503f325cbf29b83&oe=5A16ED07

Cornered Prey (71):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21317707_1509231405823283_3354363506255221028_n.jpg?oh=d9f1bee7b5e77c351b60df71a44a819f&oe=5A19DECC

Swift Strike (95), Something Familiar (133):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21314279_1509231435823280_7248061617369687878_n.jpg?oh=a21cdbaf14f09c99c9eb079ae71e6db5&oe=5A15A1BD

Bad Feeling (109), Drop Zone (126):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21192648_1508363405910083_8064182679798481867_n.jpg?oh=6726a614680ccfd720ef68390ad2f84e&oe=5A57D3BB

Tenacity (114):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21272230_1509401975806226_3126934361810863136_n.jpg?oh=606be4fe6b5f31a7da07f8496e4e25a6&oe=5A24F35B

B'Omarr Monestary (153):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21192617_1509231429156614_1996407990600295312_n.jpg?oh=44b4cf06da2b12b3aab874419f870585&oe=5A12F391

Battle Rage (136):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21231719_1509150929164664_2884835920966948313_n.jpg?oh=05e1021c962352613437c990f915e852&oe=5A141F87

Keen Instincts (135), Persuade (138):
https://scontent.fbos1-2.fna.fbcdn.net/v/t1.0-9/21231098_1509116365834787_827058011554362615_n.jpg?oh=459c0b1bf8197dd0de95ea7d9c34e008&oe=5A230B8D

I probably missed a couple, but that is going through all the ones I know about... :)

**Comment by fafranco82** [comment]
Added!!! Thank you sooo much :)
