### ISSUE TITLE
One more missing EaW card

### ISSUE THREAD

**Issue by jgoldshlag** [fafranco82/swdestinydb#150]
The last dice card:

Scatterblaster (60):
https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-0/p480x480/21740030_10209652615903204_8657303949965482698_n.jpg?oh=6c1c1c6430ff04f7ec0b41b71127cbe0&oe=5A5CD48B

**Comment by fafranco82** [comment]
Added! Thank you so much!
