### ISSUE TITLE
Deck problems

### ISSUE THREAD

**Issue by TheDarkSideHasCookies** [fafranco82/swdestinydb#152]
I just created a deck with two Gamorean Guards, and the deck builder said I had too many copies of a card. I tried it with one guard, and it worked. The Gamorean Guard is not unique, so it should not show a problem with that. Just an FYI. 

Also, if it is possible, when it does tell us something like that is wrong with our deck, it would be helpful if it told us which card was the problem card. 

Thanks, Great Product, I love the deckbuilder!

**Comment by fafranco82** [comment]
Fixed ;)
