### ISSUE TITLE
Add option to only show "needed" cards

### ISSUE THREAD

**Issue by jeffneely** [fafranco82/swdestinydb#156]
**Feature/Enhancement Request: Filter to "Show Missing"**
We already have the option to show only those cards owned; could you consider adding another filter option for the opposite?  Only showing those cards that are missing from your collection (hiding those already owned)?  This would make it easier to see what is left to acquire or trade for.
This might be a simple first step toward more granular collection management features, where users might be able to specify desired counts and such for each card.

**Comment by fafranco82** [comment]
Hello,

if you mean a filter in the collection section, that section will be changed and enhanced, I hope soon (work in progress...). But anyway, you currently can filter the collection with the text input, using 'c' or 'd' as filters. For example, if you type `c<1`, the list will only show cards that you own less than 1 (son you don't have any). Actually, it's what I do.

Best regards.
