### ISSUE TITLE
Retain filters when saving collection changes

### ISSUE THREAD

**Issue by jeffneely** [fafranco82/swdestinydb#157]
When saving any changes to your collection, the search filters are automatically reset.  This gets slower as the number of sets and cards has grown, as it causes the entire db of cards to be re-loaded by default.  
This is especially inconvenient when you just want to focus on one set or a multiple filter criteria, as you have to uncheck multiple filter boxes or rest several criteria each time. 
Consider retaining any filter conditions when saving a collection.
(this could also reduce load and speed up the UI, as it probably means smaller query results vs. returning all rows by default each time -- depending on the underlying implementation ;-)

**Comment by fafranco82** [comment]
Yes, it's one of the several things I want to improve with the restructuring of collection section. But maybe this can be done easily and qucikly in current code... I will take a look at this.

**Comment by fafranco82** [comment]
Done ;)
