### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by sanchezelton** [fafranco82/swdestinydb#168]
Encrypt connections using HTTPS. While I agree it is simpler and easier to setup the site without one, there's no reason for a site since Let's Encrypt (shameless plug, but valid) is a free and open source CA.

**Comment by fafranco82** [comment]
HTTPS has been active almost from beginning... https://swdestinydb.com/

Only it is optional and there is no automatic redirect from HTTP tp HTTPS.

Best regards.
