### ISSUE TITLE
Add a french version of the website and cards

### ISSUE THREAD

**Issue by Salem2612** [fafranco82/swdestinydb#18]
I can help you to add a french version (and maintain it) of the website and the cards. Just tell me the format of the file you want (JSON, XML... ?).

**Comment by fafranco82** [comment]
I would be very apreciated!! If your used to use github, you can fork this project, edit the file `src/AppBundle/Resources/translations/messages.fr.yml` and make a PR :) . It is not yet in the repo, but I will added it in a while.

For card data, I use the http://github.com/fafranco82/swdestinydb-json-data repo. You will need node and coffee installed, Fork the repo, clone it to local, and run `coffee update_locaes.coffee fr` to create and merge files for `fr` translation, and edit all the files inside the dir. Just don't change `code` attribute.

Thank you for the offer :)

**Comment by fafranco82** [comment]
(I'll keep this issue open for a while if you have more questions to ask)

**Comment by Salem2612** [comment]
I use to use github. I'll make these changes and a PR when the french version of SW Destiny is available to get the official keywords.

**Comment by fafranco82** [comment]
Perfect! I'm eager to see it :) My spanish translation is also waiting for the release in Spain....

**Comment by fafranco82** [comment]
@Salem2612 I've just been mailed by another user who wants to help with French translation. If you wish, I can sent him some contact info of you so you can talk each other.

**Comment by Salem2612** [comment]
@fafranco82 You can say to him to contact me here or on the french fanforum : http://starwarsdestinyfr.forumactif.com/
I'll manage the french people that want to contribute to the translation. The french rules are online, I have a few new keywords !

**Comment by fafranco82** [comment]
Hi there,

I've just pushed a big update concerning translations. I've changed the format of translation files from YML to XLIFF. This files are easier to maintain because can have extra info and there are tools designed to use this kind of file.

With your translation work in progress, this is the necessary steps to keep your work safe:

* Copy your translation files (`messages.fr.yml`) to another place, because the file was deleted in the repository and will be deleted too in your working copy.
* Pull upstream master and run again `composer install`
* Copy back the `messages.fr.yml` to the same location it was before.
* Run `php app/console translation:extract --config=AppBundle fr`. This will take into account the translations made in `messages.fr.yml` and then transform the file in XLIFF format, renaming it to `messages.fr.xliff`.
* Run `php app/console server:run` and then navigate to `/_trans` path.
* Select `AppBundle`, `messages` and `fr` in the select inputs on the top. You can edit here the translations. They will be automatically saved on the file when the textarea lose focus.

I hope you can understand this change... whenever a new translation key will be needed, it will be easier to translate it in all languages this way.

**Comment by Salem2612** [comment]
OK thank you :) I am fighting with `install composer` on Kubuntu.

**Comment by Salem2612** [comment]
When i execute `composer install`, `php app/console translation:extract --config=AppBundle fr` or `php app/console server:run` I get the following error : `A string value must be composed of strings and/or numbers, but found parameter "website_url" of type NULL inside string value   
  "es.%website_url%".`

I pulled your repo and mine is up to date. I don't know anything about composer and php. Could you please help me ?

**Comment by fafranco82** [comment]
check if in `paramaters.yml` the value of `website_url` is defined. I edit my `hosts` file to add different server names pointing to 127.0.0.1, something like this:

```
swdestinydb.local      127.0.0.1
fr.swdestinydb.local   127.0.0.1
```
So, with these server names, the `website_url` param would be `swdestinydb.local`.

I forgot this is necessary to run the server in different languages. I will edit soon the README with this info.

**Comment by fafranco82** [comment]
Any news on this? I'm eager to see swdestinydb in more languages :)

PD: I love languages...

**Comment by Salem2612** [comment]
Hello,

I had problems with install composer. I didn't know what to put in the
several fields that it asks to fill. I didn't have time to try it again
with the new updates of your tutorial. I am a bit depressed because it took
me several hours for not managing to put few strings in a file... I'll try
it again when I have time. If it succeeds I'll put the translation of the
cards.

2016-12-16 10:17 GMT+01:00 Francisco Franco Eslava <notifications@github.com

**Comment by fafranco82** [comment]
@Salem2612 

I've jsut changed the way the site can be translated. Now it's easier, doesn't need to install a local copy and doesn't require any programming skills ;)

The only thing I need is your name and email to sendin you an invitation to the translation platform ;) You can send me these to webmaster@swdestinydb.com.

(More details in the end of the updated README)

**Comment by Salem2612** [comment]
@fafranco82 : French translation done !

**Comment by fafranco82** [comment]
Site in french available now on http://fr.swdestinydb.com ;)

You need to push your changes to github and then creating a Pull Request from your project web page.

* To push: `git push origin master`

About card images, I want to have images of the different languages, but by now I d'n't know how to do it without interferring performance. Anyaway, all the images are being stored in a binary repository on bitbucket (a site like github but for binary files). I will send you an invitation to the project to the same email for translations.

**Comment by Salem2612** [comment]
The french translation of the cards are available on the other json-data repo. Be careful because I didn't check the json with the python script. I hope chars like "é", "ê" and ' will work.

**Comment by fafranco82** [comment]
It was all ok! Cards up ;) Merci beaucoup!

**Comment by Salem2612** [comment]
Thank's ! I close the issue !

**Comment by Salem2612** [comment]
I have added all the french cards to bitbucket.
