### ISSUE TITLE
Minor Errors & Rest of Cards Shown

### ISSUE THREAD

**Issue by Mega-Silver** [fafranco82/swdestinydb#181]
Ketsu is labeled with a shield where she has a resource side.

Strength in Numbers is 2 cost, not 1.

This guy has all the cards in order except for Saw Guerra.

https://www.facebook.com/media/set/?set=pcb.2043668395855766&type=1

**Comment by fafranco82** [comment]
Thanks!!! Errors fixed! I see that album, only I hadn't time to add them all until now ^^U
