### ISSUE TITLE
i cannot add cards to deck

### ISSUE THREAD

**Issue by prozz** [fafranco82/swdestinydb#19]
after picking side im into deck editor. then whenever i pick a card from a drop down search (like a first order storm trooper) i got quantity of 0 of it to add. im pretty familiar with netrunnerdb, so this is some kind of odd behaviour just in this version - not user bug id say ;)

**Comment by fafranco82** [comment]
The card modal dialog is linked with the behaviour of the card list in the builder, so you can select only the maximum number of card your are allowed.

There is an option (active by default) to show only owned cards (and thus, to allow only owned cards to be added). You can add cards a dice to your collection in the "My collection" page, or uncheck de "Show inly owned" cards options below "Options" dropdown menu.

There is already an issue to make more visible this issue.

**Comment by prozz** [comment]
is there an easy way to add whole set to my collection?

**Comment by fafranco82** [comment]
You can build decks with cards you don't owned. Just uncheck the "Show only owned cards" option.

Also, you can bulk add cards to your collection from starter lists, so you don't have to add one by one the cards contained in an starter.

Adding a whole set to your collection does not seem realistic use of case for me... Maybe, if someone doesn't want to use the collection tracker at all, I may add an option in his profile page to make "Show only owned cards" unchecked by default. I will think about that.

**Comment by prozz** [comment]
thanks for long explanation. i thought i tried that checkbox, but at the same time site is extremely laggy lately and it's hard to use at all. possible misuse on my part.
