### ISSUE TITLE
FN-2199

### ISSUE THREAD

**Issue by JacerOrigins** [fafranco82/swdestinydb#192]
The FN-2199 is a 10/13 cost card but when you select it to take part of a deck it counts it as a 12/15 cost.

**Comment by jmcnett010** [comment]
There was an errata that increased the card's cost.

**Comment by Worldedit05** [comment]
Page 23 of the Rules Reference

https://images-cdn.fantasyflightgames.com/filer_public/85/95/8595ce20-1ac1-45bd-96d3-c6089740e28d/swd_rules_reference_16compressed.pdf
