### ISSUE TITLE
Site loading extremely slowly

### ISSUE THREAD

**Issue by Krezminski** [fafranco82/swdestinydb#193]
The past day or two I've noticed the site taking a long time to load any page, especially when saving a decklist. 

Others have experienced it too:

https://www.reddit.com/r/swdestiny/comments/7rd72x/swdestinydb_extremely_slow_not_loading_at_all/

**Comment by fafranco82** [comment]
Just upgraded the server to have more memory and cpu. It seems it's going ok now.

**Comment by Krezminski** [comment]
Awesome! Thank you, it is indeed working normally for me. Closing.
