### ISSUE TITLE
Can’t copy deck

### ISSUE THREAD

**Issue by phatram32** [fafranco82/swdestinydb#195]
I’m trying to copy a deck from one posted and receiving an error message: cannot import deck without format.
![9ad7f17a-bd1b-46d6-960c-e37b4e19bb0a](https://user-images.githubusercontent.com/35791204/35370926-e2b49c1e-015e-11e8-906f-3c09bf427415.png)

**Comment by fafranco82** [comment]
Fixed!

**Comment by phatram32** [comment]
Thanks!
