### ISSUE TITLE
My Collection: Add Starter Pack adds wrong card for Luke Set

### ISSUE THREAD

**Issue by rarius** [fafranco82/swdestinydb#199]
On the My Collection page, clicking Add Starter Pack: Luke Skywalker (Legacies) adds one copy of "Quick Draw" to the collection, in addition to the other starter set cards.  The physical starter set does not include any copies of "Quick Draw"; instead, it has one copy of "Quickdraw Holster".

**Comment by fafranco82** [comment]
Fixed! Thanks for the report.

**Comment by clowe55** [comment]
This issue seems to have returned.
