### ISSUE TITLE
Request: extend/remove auto logout timeout

### ISSUE THREAD

**Issue by golike** [fafranco82/swdestinydb#210]
I'm a frequent user, and more than once have been frustrated by leaving a new deck build window open in process, only to come back an hour or two later with all my changes lost due to the app logging me out. Is there a reason this timeout is so short, or really why it exists in the first place?

**Comment by fafranco82** [comment]
Hi,

every application has a session timeout. SWDB in particular has a session timeout as longer as the projects it was based on: NetrunnerDB and ThronesDB. But there is two solutions about this:

- Use "Remember me" option when logging in..
- There is an automatic process running when in builder page, autosaving changes made to the deck from last time was saved or autosaved. If your session expires and you reload the page, you will see a notice that your deck has unsaved changes. So you can click on "History" tab, an click "Revert" in the first row of history log.
