### ISSUE TITLE
Tactical Mastery in Trilogies

### ISSUE THREAD

**Issue by Mega-Silver** [fafranco82/swdestinydb#211]
Tactical Mastery is a part of the Trilogies cycle as well.

https://boardgamegeek.com/thread/1847252/cards-and-dice-box

**Comment by fafranco82** [comment]
Yes, that card and other seven cards from Awakenings and Spirit of Rebellion were reprinted in Two-Player Box. These reprints are known by the database. Take a look at the card info box on the card page of Tactical Mastery (Awakenings version):

![image](https://user-images.githubusercontent.com/5708531/36583383-cc8dfb82-1875-11e8-9a1b-0c5094bb8b27.png)

And check out the card legality: it's legal in Trilogy format.

The same for 2PG box version:

![image](https://user-images.githubusercontent.com/5708531/36583395-da694982-1875-11e8-9256-9651e728cd28.png)

In the deck builder this works considering only the original print. But, in terms of your collection, the amount of reprinted versions you own are added up to the original print amount, so if you don't have an AW Tactical Mastery but have 2 TPG Tactical Mastery, you can add it to your deck even when using "Only cards I owned" option. Take a look in this example, building a Trilogy villain deck. Tactical Mastery appears as eligible to be included in my deck:

![image](https://user-images.githubusercontent.com/5708531/36583439-06d133fe-1876-11e8-932e-f6caa61e0907.png)

**Comment by Mega-Silver** [comment]
Sorry I wasn't clear in my initial post, was trying to post it too quickly.
The issue is that it doesn't show up in the Trilogy only listings. I just
tried it now and it's not listed. Same with the other 7 cards. I have
everything non-Legacies unselected so the list won't be so long to scroll
through, and with so many cards to consider, I overlooked Tact Mastery (and
now looking at it, Doubt as well). I have never used the site to list my
collection, so that feature hasn't come up for me in that manner. It just
seemed odd that it wasn't relisted in the Two Player Set.
