### ISSUE TITLE
Filters should also return counts

### ISSUE THREAD

**Issue by mattsigal** [fafranco82/swdestinydb#22]
When you filter your cards (e.g., only view Hero and Neutrals), it would be great if either at the top or bottom of the page it said how many cards are currently viewed (either out of the total pool or your collection).

For example, maybe I have 100 cards in my collection. I filter for Villain and Neutrals, it would be great if swdb told me: Showing 65/100 cards.  This would be useful to quickly see how balanced a collection is, in terms of card quantity.

**Comment by fafranco82** [comment]
Do you mean in the collection tracker? Or maybe in the deck editor?

**Comment by mattsigal** [comment]
I was thinking in the collection tracker. So here I am filtering for Neutral and Hero cards that I own:

![screen shot 2016-11-21 at 11 57 41](https://cloud.githubusercontent.com/assets/1421758/20492193/d642f72a-afe1-11e6-943f-51b4dd7eef89.png)

Either above the table or below (probably below), it would be really helpful to see the number of cards returned by the filter (out of either the total cards in my collection if "Show Only Cards in my Collection" is checked, or the total cards in the game if it isn't).

**Comment by fafranco82** [comment]
Interesting. I will do this in the future. Thanks for the idea.

**Comment by n8lightfoot** [comment]
I would like to see a sort feature on the collections so we can have the most Favorited/commented/etc sorted out to the top

**Comment by fafranco82** [comment]
Done what @mattsigal said in 61a51fe5f987f40a4c21f65c2fc5cc6cb0108fe1.

**Comment by mattsigal** [comment]
I think this is almost functional, but in Chrome (running a recent Canary build), it returns %count%:

![screen shot 2016-12-20 at 18 22 50](https://cloud.githubusercontent.com/assets/1421758/21372544/d78d3e86-c6e5-11e6-9d16-b3c1a7e8988c.png)

**Comment by fafranco82** [comment]
Fixed ;)
