### ISSUE TITLE
Aayla Secura not sorting properly

### ISSUE THREAD

**Issue by aurelius47** [fafranco82/swdestinydb#234]
i just noticed while building a deck that when you sort characters by cost Aayla Secura still takes the position as if she had her old cost of 9/12 instead of 10/13.

![aayla sort issue](https://user-images.githubusercontent.com/41307475/42782601-4532a210-88fe-11e8-9c04-7fe62ff4de8b.JPG)

**Comment by fafranco82** [comment]
Thanks!
