### ISSUE TITLE
Sorting collection on Health in ascending order yields incorrect results

### ISSUE THREAD

**Issue by stopfstedt** [fafranco82/swdestinydb#24]
![selection_070](https://cloud.githubusercontent.com/assets/1410427/20502123/91ff1fa2-aff1-11e6-9bce-803f56d4d1ef.png)

Sorting in descending order works fine. Looks like an issue with ForerunnerDB. 

For debugging purposes, see this line: https://github.com/fafranco82/swdestinydb/blob/master/src/AppBundle/Resources/public/js/ui.collection.js#L460

This may possibly be related to Irrelon/ForerunnerDB#59

The sort order object that's being passed in this case is `{ 'health': 1, 'name': 1 }`.

**Comment by fafranco82** [comment]
I've tried updating ForerunnerDB to the last version and works even worse... Maybe I must rely on custom javascript sorting instead Forerunner sorting (the same with points issue #7 )

**Comment by stopfstedt** [comment]
I tried to isolate the issue with forerunner db, see this stripped-down example: https://jsbin.com/sogoyul/edit?html,js,output
Seems like ForerunnerDB is sorting correctly, there.

Perhaps the bug is elsewhere after all.
