### ISSUE TITLE
Feature Requests: Deck Builder update request

### ISSUE THREAD

**Issue by ShivanEmbrace** [fafranco82/swdestinydb#245]
An AtG update is needed to deck builder to allow 4 copies of Tie Fighter and X-Wing to be included in a deck. Also the Battle Royale format is gaining popularity so including that in the format screen of Deck Builder would be advantageous

**Comment by fafranco82** [comment]
Max quantity fixed. :)

About Battle Royale... I don't even know what Battle Royale format is... anyway, I guess is not an official format, so it's unlikely it will have support in swdb, sorry.

Best regards.
