### ISSUE TITLE
Vader's Fist error

### ISSUE THREAD

**Issue by mlogie** [fafranco82/swdestinydb#247]
The 6th side on Vader's Fist is listed as blank but should be 2 shields

**Comment by rdonnelly** [comment]
PR submitted: https://github.com/fafranco82/swdestinydb-json-data/pull/142

PR's welcome in the future. 😉

**Comment by mlogie** [comment]
Will do next time, though this is the first error I've ever seen

**Comment by fafranco82** [comment]
Fixed! Thanks to both of you :)

**Comment by mlogie** [comment]
This was resolved a while ago.  Just tidying up.
