### ISSUE TITLE
Bug: Compare decks function leads to error page.

### ISSUE THREAD

**Issue by mattsigal** [fafranco82/swdestinydb#25]
When trying to use "Compare Decks" feature, instead of actually seeing a diff of the two decks, I get redirected to an error page.

For example, with two decks selected:

<img width="1027" alt="2016-11-21 1" src="https://cloud.githubusercontent.com/assets/1421758/20508097/2ddddab8-b02d-11e6-8133-3fffc6aa1996.png">

Click "Compare Decks" brings me to a 505 error:

<img width="795" alt="2016-11-21" src="https://cloud.githubusercontent.com/assets/1421758/20508107/37054504-b02d-11e6-9de6-54af66303f77.png">

**Comment by fafranco82** [comment]
Fixed. e609553b542e17722ea24328d0d0ccee5829c62e
