### ISSUE TITLE
Lightsaber Mastery

### ISSUE THREAD

**Issue by lefthighkick** [fafranco82/swdestinydb#260]
I apologize if this is the wrong spot for suggestions.

When you add the Lightsaber Mastery plot to a deck, it would be sweet if it created an extra section in your list just like Upgrades/Downgrades/Support/Events do so that we can include the two Move events it allows while being distinct from the rest of our events.

Thanks for all the great work!!

**Comment by fafranco82** [comment]
Done!!! (a few days ago ^^U)
