### ISSUE TITLE
Deflect(Awake 145) says it has been reprinted in Allies of Necessity

### ISSUE THREAD

**Issue by MalaciousMawloc** [fafranco82/swdestinydb#262]
Says it is #15 in Allies, where that is the Flank reprint.

**Comment by rdonnelly** [comment]
Fix is coming, thanks for the report!

https://github.com/fafranco82/swdestinydb-json-data/pull/164

**Comment by fafranco82** [comment]
Thanks to both of your fothe report and the fix!
