### ISSUE TITLE
Draw Deck Warning

### ISSUE THREAD

**Issue by tabwgt** [fafranco82/swdestinydb#264]
Giving Warning on deck draws....states (Draw Deck must be 30 Cards)..When I do have 30 cards in draw deck. Some decks get saved with out if you unselect the first three sets under the Sets Tab in the EDIT screen...

Suggest to separate the reprints only in standard and have 2 versions of same card when select INFINITE..

**Comment by tabwgt** [comment]
Found reason I believe....Event-Move cards are giving the warnings when put into decks

**Comment by fafranco82** [comment]
Fixed :)
