### ISSUE TITLE
Update Extrapolation

### ISSUE THREAD

**Issue by Rafaelsca** [fafranco82/swdestinydb#267]
I believe that the update that was made today has overwritten the costs (and maybe the subtypes too) of the character cards with the same name, but of different collections.

**Comment by fafranco82** [comment]
What do you mean? The update was for the new holocron documents. Points of old "black" sets has been reduced in nearly every character... but only in Infinite format. Subtypes of older characters without previous subtypes was added to them via errata. It should works fine while building decks... but maybe you refere to a bug when listing cards in "Full card" display mode. In the "Balance of the Force" box, the points of the first character in the list are shown in every one else... I'm working on fixing this.

**Comment by Rafaelsca** [comment]
I was referring to this same problem (from "Balance of the Force"), but I thought it was a problem exclusive to the cards that were updated.

**Comment by fafranco82** [comment]
Ok, then I'll close this because this problem was resolved yesteday :)
