### ISSUE TITLE
Tabletop Simulator JSON failing to import Convergence-based decks

### ISSUE THREAD

**Issue by happyclan** [fafranco82/swdestinydb#272]
First, thank you for your work.  I'm noticing if I have a deck with any Convergence cards, the JSON for Tabletop Simulator has empty Card IDs for those cards.   I can fix it myself by taking a REST URL.  Example: https://swdestinydb.com/card/09010  If I take that 09010 and put it into the Tabletop Simulator JSON then it'll work fine.  It seems your site isn't exporting those IDs into the JSON file.  

Thanks!!

**Comment by fafranco82** [comment]
Yes, TTS card IDS were not in swdestinydb until now that someone gave them to me right now :)

**Comment by happyclan** [comment]
You're a champion.  Thank you so much for the fix and all the hard work.  Keep going!!
