### ISSUE TITLE
Error on card: Droids' Day Out

### ISSUE THREAD

**Issue by jmarkbacon** [fafranco82/swdestinydb#285]
Droids' Day Out is showing 5 instead of 3 for how many droids you need to activate to get the effect.  Wasn't sure if this is the place to report that or not.  
![Droid's day out](https://user-images.githubusercontent.com/53532791/62227692-05722d80-b382-11e9-99f3-830614ad3daa.PNG)

**Comment by mlogie** [comment]
Fixed. Please close @fafranco82
