### ISSUE TITLE
Images Missing for Convergence Starters

### ISSUE THREAD

**Issue by joemasilotti** [fafranco82/swdestinydb#291]
Images for the cards from the [General Grievous](http://swdestinydb.com/card/09021) and [Obi-Wan Kenobi](http://swdestinydb.com/card/09057) starters are missing. I noticed that cardgamedb.com doesn't have those sets listed either.

Is there any way to get "custom" scans in for these cards without going through cardgamedb.com? There are quality scans that exist and I can pass off if needed.

If this already exists in the code let me know, I'm happy to chip in if possible!

**Comment by fafranco82** [comment]
Yes, of course!! You can send them to me to webmaster@swdestinydb.com (or a link where to find them). Thanks!!

**Comment by joemasilotti** [comment]
Great, thanks! Expect an email soon.
