### ISSUE TITLE
All decks and the collection appear to be empty

### ISSUE THREAD

**Issue by aramaziakin** [fafranco82/swdestinydb#294]
All the decks that I try and open/edit are completely empty, both mine and other peoples, but the text files download fine. The collection tab is completely empty too. Everything was working fine yesterday and I've tried on both Chrome and Edge, logged in and logged out.

**Comment by fafranco82** [comment]
Fixed with 5b22437ec7a3143a3766ff7f7477b0074f5fb260

Thanks for reporting
