### ISSUE TITLE
[Awakenings] All cards

### ISSUE THREAD

**Issue by Salem2612** [fafranco82/swdestinydb#3]
The list of all 174 cards of Awakenings is available on the french fanforum :
http://starwarsdestinyfr.forumactif.com/t14-awakenings-les-174-cartes

You can find the ID f the card, its english name, "X" if it has a Die, "U" if it is Unique, and its rarity.

**Comment by fafranco82** [comment]
Thanks for the info, but I need all card info to be added in DB, not only its name.
