### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by QuinnH2O** [fafranco82/swdestinydb#302]
The "forgot your password?" button says it sent an email but I'm not getting the email, yes I've checked my spam.

**Comment by fafranco82** [comment]
Did you try recently? There was (or still there are) some problems with the mailing system that I hope it was fixed yesterday... 

Meanwhile, you can mail me to webmaster@swdestinydb.com and tell me what password want to use and I'll set it for you.

**Comment by QuinnH2O** [comment]
Just tried yesterday, I will try again after the 24 hour timer is up.

**Comment by fafranco82** [comment]
Password changed ;)
