### ISSUE TITLE
Can't select the elite option (2 dice)

### ISSUE THREAD

**Issue by TinyFAST** [fafranco82/swdestinydb#328]
I am trying to create a new deck (hero>infinite). When i select my first character, I try to select the 2 dice option (elite) and it won't work. One die works perfectly. Tried again with the second character and it is the same: 1 die only.
The same happens whether it's Villain or Hero and with all deck formats.

**Comment by fafranco82** [comment]
@jlannoy can you take a look on this?

**Comment by jlannoy** [comment]
Hi @TinyFAST. I just checked, ask to other players, and everything seems fine.

Which browser are you using? Try to force reload the page. I've seen on Safari someone had to cmd+option+R the page, Safari was keeping too old files. You can also try Ctrl+F5 or Cmd+F5 on Chrome or Firefox...

**Comment by TinyFAST** [comment]
Hi. Thanks for getting back to me. 

My office computer (PC) uses Chrome v. 83.0.4103.97 (64 bits). Doing Ctrl+F5 did solve the issue. 

I thought I would see if I had the same problem on my personal computer (PC) which has Chrome v. 87.0.4280.88 (64 bits) and Microsoft Edge v. 87.0.664.66 (64 bits). To my surprise, the only option it gives me for a character is 0 die (!). On both browsers. 

I tried Ctrl+F5 and clearing all browser date, in both cases the issue is still there (no 1 or 2 dice options). Tried with a computer restart and the issue is still present. 

Thanks.

**Comment by jlannoy** [comment]
I think it's unrelated.

You should check your collection versus the filters that were applied to your deckbuilding list ; if you see what I mean. You can have this : 
<img width="177" alt="Capture d’écran 2020-12-22 à 23 57 53" src="https://user-images.githubusercontent.com/3064433/102940875-9b47b480-44b1-11eb-8ce4-c9613c1e42f9.png">
When you didn't point the dice you own in your collection (only the cards), and the filter "Show only owned cards" (in the options) is checked. On my picture below, if I uncheck it, I'll have the one or two dice proposal.

Let me know if you find it :)

**Comment by TinyFAST** [comment]
I just changed my personal computer. I didn’t bother to check the filters since I’ve been using the same settings for a while. 

I feel foolish :-)

Thanks for your help. It is greatly appreciated. Have a great holiday.

**Comment by fafranco82** [comment]
No problem ;)
