### ISSUE TITLE
Not receiving Verification Email

### ISSUE THREAD

**Issue by lancejayn** [fafranco82/swdestinydb#329]
Hi there!

I have been trying to create an account on swdestinydb.com. When I try to login the website says that my account is disabled. I have been trying to get the website to resend the registration email but it has never come through to me. Can you help me with this? My username is lancejayn and the email should be lancejayn@gmail.com

Thank you!

**Comment by fafranco82** [comment]
I've just activated your account.

**Comment by lancejayn** [comment]
Thank you Francisco! I appreciate your help!

Lance
