### ISSUE TITLE
Subtype Search does not work

### ISSUE THREAD

**Issue by jamesdowdall** [fafranco82/swdestinydb#33]
Searching with any of the existing subtype criteria in either search page does not return results: http://swdestinydb.com/search

E.g. http://swdestinydb.com/find?q=b%3Aweapon does not return any weapons (none of the other subtype criteria return anything either).

This appears to be because subtype has not been implemented. Data is still all held in span.card-type as "Upgrade - Weapon."

![image](https://cloud.githubusercontent.com/assets/7204730/20593180/476499ec-b229-11e6-8ad2-7e64ddcb78b3.png)

**Comment by fafranco82** [comment]
Fixed with 5253c21ef537594e2bf65348ce0312c5aca140b1.
