### ISSUE TITLE
Not getting the registration email

### ISSUE THREAD

**Issue by gaborszoke** [fafranco82/swdestinydb#330]
Hi,

I am new to this site, so please excuse me if there is a separate thread where this could be reported.

I tried to register on the swdestinydb site already with two different email addresses, but I am not getting the registration activation emails. Even clicking on "Click here" if you are not getting the registration email does not help. What can I do?

Thanks in advance for your help!

**Comment by govem** [comment]
i have the same problem

**Comment by fafranco82** [comment]
I've manually activate your accounts.
