### ISSUE TITLE
Bug: Not receiving confirmation email for new account

### ISSUE THREAD

**Issue by nschuman027** [fafranco82/swdestinydb#343]
Hi, I created a new account and never received a confirmation email to activate it. I tried resending it but no luck.

Thanks

**Comment by JeanPonceII** [comment]
Hi, same thing here, I've been trying to create a new account for one or two week, using 2 email adress... no email confirmation :(

**Comment by fafranco82** [comment]
@nschuman027 your account is now activaded

@JeanPonceII what's your account? I try to find it but without success.

**Comment by fafranco82** [comment]
Nevermind, I see the account name in the other issue. I'm closing this one.
