### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by smitch35** [fafranco82/swdestinydb#39]
Just wondering if there might be a more indepth install guide for a local copy at any time?

**Comment by stopfstedt** [comment]
@smitch35 what's missing from the current install instructions/where are you stuck? thanks.

**Comment by smitch35** [comment]
Well I'm trying to do a local install and following the instructions seem ok but some odd issues popped up during certain steps.
Everything before this step worked ok.
1.) composer install didn't work, following the guide link to install composer it made a composer.phar executable so the I had to do ./composer.phar install to work.  I wasn't quite sure how to answer some of the questions here since I was doing a local install I stated the database url as 'localhost' and filled out the website url as localhost as well.  I also had to put false for all the aws entries so that the later commands wouldn't use them.
2.) run php app/console doctrine:database:create.  This command created a database called ocalhost and not localhost, not a big deal but seemed odd.
All other php app command seemed to run.

I then had to edit my document root in my apache install to point to the swdestinydb web folder I've kind of gotten the site to load but none of the graphics seem to be applying so I'm wondering if I've messed up a connection string to the db.

That's about the only places I'm having issues.  I think a lot of it is related to a localhost install but I'm not sure.

**Comment by stopfstedt** [comment]
thanks for the quick feedback.

1. `database_url` format is like this `'mysql://dbuser:dbpassword@host:port/dbname`. in my local environment, i run mysql on localhost (IP 127.0.0.1), my db user is `root` with password `XXXXXXXX` (not really) and db name is `swdestinydb`. so my database_url is 'mysql://root:XXXXXXXX@127.0.0.1:3306/swdestinydb` 

2. `ocalhost` must be a typo. check your `app/config/parameters.yml` file and correct it there.

re: missing pictures. i don't have these either. i presume that's what the AWS S3 bucket is for. haven't dug deep enough into the code base yet, perhaps @fafranco82 can comment?

**Comment by smitch35** [comment]
Thanks for the quick response.  I'm not seeing the ocalhost typo but since my db is already called that i'll just point the databaseurl to that.

**Comment by stopfstedt** [comment]
don't forget to clear caches after modifying the parameters file. 
`php app/console cache:clear -e prod`

**Comment by smitch35** [comment]
Thanks for that too!  I'm really new to a lot of this so I'm sure everything is actually broken because of me.

**Comment by stopfstedt** [comment]
If  your local Apache serves up an empty page, or something saying "internal server error/500" or the likes, then you should first turn enable error message to be displayed.
In your PHP configuration file (`php.ini`), set `display_errors` to `on`, then restart Apache. this should cause PHP error messages to appear on any page that you're loading, which hopefully will shed some light.

On a more general note, check that your local PHP environment fulfills all the basic requirements to run a Symfony 2.7 application, such as this.
https://github.com/symfony/symfony/blob/2.7/README.md#requirements

**Comment by w1nterl0ng** [comment]
made it all the way through the install, when I fired it up, it fails on AWS/S3 integration.  I left those null on the composer install because I thought they were only for production deployment.
Is an AWS/S3 account required for development?  If not, is there a setting besides null that will work?

**Comment by stopfstedt** [comment]
@w1nterl0ng that's good feedback, i'm filing a PR for better defaults on these AWS keys.

**Comment by fafranco82** [comment]
Thanks!!
