### ISSUE TITLE
Sign-in errors

### ISSUE THREAD

**Issue by dahbearz** [fafranco82/swdestinydb#41]
Something seems to be wrong with whatever is keeping track of sessions. Despite signing in correctly, I am redirected to the homepage where the site does not recognize me as being signed in. If I use a ad-blocker, this happens less often. However, if I use an ad-blocker, occasionally I will receive a bad CSRF token error. Whatever is causing these errors seems to be the reason why if I try to edit/create a decklist the app will ask me to sign in - even though I've already signed in and the profile dropdown in the nav recognizes me as being signed in.

**Comment by fafranco82** [comment]
I've been testing now... I have the same problems except when I log in with "remember me" option... do you use the "remember me" option?? Try to use it,

Anyway, I will investigate further why loggin without "remember me" throw errors or redirections.

**Comment by dahbearz** [comment]
I have tried the "remember me" option and will get different results depending on how RNGesus feels.

**Comment by ShlinkLincoln** [comment]
This is happening to me to.  User ID on site:  shlink.  

I've tried IE and Firefox on PC and Safari on my iphone.  It lets me sign in (remember me or not) but cannot see other pages on the site.  It always give me the /login page no matter where I click.

Upon registering I also got the CSRF error but it finally let me register after about 3 or 4 attempts.

Thanks.

**Comment by fafranco82** [comment]
I hope all this issues are gone by the migration scheduled for tomorrow ;)

**Comment by fafranco82** [comment]
Server migrated. I can't replicate this error in the new server, so I close this issue :)
