### ISSUE TITLE
Translation script doesn't create all .twig files for localization

### ISSUE THREAD

**Issue by siema** [fafranco82/swdestinydb#42]
After seemingly finishing Polish translation I've noticed that some subpages crash (500) with Polish language on. When starting a debug instance it turns out that the command in README
`php app/console translation:extract --config=AppBundle <locale>`
Doesn't create all .twig files.

Example error after trying "My decks":
`Unable to find template "AppBundle:Builder:no-decks-text.pl.html.twig" (looked into: /home/siema/projects/php/swdestinydb/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form) in AppBundle:Builder:no-decks.html.twig at line 7.`
Stacktrace: https://pastebin.com/1nUV6AmV

Indeed, there is no such file: https://pastebin.com/a9PawceM
It works after copying the English one, but I think those texts should be localized like the others.

And I'm not sure if it's related (because there is no error), but some strings aren't included in the translation as well:
![swddb1](https://cloud.githubusercontent.com/assets/537808/20968775/4f552812-bc86-11e6-837e-b86812fd2fc5.png)
![swddb2](https://cloud.githubusercontent.com/assets/537808/20968794/7182fda6-bc86-11e6-97ea-98b8e84962ac.png)
![swddb3](https://cloud.githubusercontent.com/assets/537808/20968831/93125200-bc86-11e6-9ad8-cfce4cbe51aa.png)
Maybe some more. I'm 100% sure those strings weren't available for translation in /_trans panel.
The same applies to other translations as well (in Spanish version those labels are in English as well)

**Comment by fafranco82** [comment]
The `no-decks.html.twig` file(s) is my fault. I forgot them. As these page has a lot of text within them (and with images), I've decide to import into the main page, `no-decks.html.twig`, a localized file, so in English is `no-decks-text.en.html.twig`, Spanish is `no-decks-text.es.html.twig` and so on...

It's the same with `footer.<locale>.html.twig', that I didn't forget to create polish version but I've forgotten to mention it... You can translate `footer.pl.html.twig` as well, inserting the credits for translation right after the credits of the author ;)

About user forms... it's a third party library that is supposed to be localized... but it is not completely, I'm afraid.

I will update README to reflect this.
