### ISSUE TITLE
Error when trying to edit profile in Polish

### ISSUE THREAD

**Issue by siema** [fafranco82/swdestinydb#43]
This one is a kind of multi-issue, which I was not sure about how to qualify.
First of all, in production, with Polish language on, I'm getting 500 when trying to edit my user profile. Not sure if related, but with Spanish and French, it works, but is still in English.

In my local instance however, I can't enter this panel at all. In any language. I'm getting this error every time:
`Variable "factions" does not exist in AppBundle:User:profile_edit.html.twig at line 68`
Stacktrace: https://pastebin.com/1ggTDfHs
After opening the file in question, it looks like all strings are hardcoded. I'm not a php expert enough to check why factions are empty though...

**Comment by fafranco82** [comment]
I will see it... maybe it's a bit of code not adapted yet... I'm sorry

**Comment by siema** [comment]
No need to apologise, looks like some typo or something :)

**Comment by fafranco82** [comment]
Fixed :)
