### ISSUE TITLE
Everytime Collection is saved, redirection to login

### ISSUE THREAD

**Issue by dave-null** [fafranco82/swdestinydb#44]
Everytime I am trying to save my collection I am redirect to the login and it is not saved. This is very annoying. I have to login multiple times, before I can see my collection again.

**Comment by fafranco82** [comment]
I've investigating this now... As I explained in #41, it is kind of weird, but it seems a problem when you don't use the "remember me" option. Try to use it while I'm searching for the solution of this enigma.
