### ISSUE TITLE
Error when importing data

### ISSUE THREAD

**Issue by siema** [fafranco82/swdestinydb#47]
When I tried recreating local environment from scratch, after merging recent commits, I keep getting this error:
```
  [Exception]
  Missing key [cgdb_id_start] in {"code":"AW","date_release":"2015-12-01","name":"Awakenings","position":1,"size":174}
```
Full log: https://pastebin.com/fvT9kvZ5

**Comment by fafranco82** [comment]
Sorry, I forgot pushing my json-data repo. You can pull it now into your local copy.
