### ISSUE TITLE
Deckbuilder: Cannot Select Elite/2-Dice Finn

### ISSUE THREAD

**Issue by zliniguez** [fafranco82/swdestinydb#5]
*Summary*
 * When creating a deck user is unable to add the Elite/2-Dice variation of Finn.

*Steps to Reproduce*
1. Add two Finn cards to collection
2. Create Hero deck
3. Click to add "2 (dice)/Elite" Finn to deck.
4. Observe that non-Elite/1-Dice version is added.

**Comment by fafranco82** [comment]
Fixed!
