### ISSUE TITLE
Text File Download on SocialController 

### ISSUE THREAD

**Issue by w1nterl0ng** [fafranco82/swdestinydb#56]
When I am running locally, clean install, the text file download from Social Controller throws this error. ```Variable "factionNames" does not exist in AppBundle:Export:plain.txt.twig at line 4```

It seems to work on the production website.  Can anyone else recreate this error?

**Comment by fafranco82** [comment]
Do you pull changes from github?

If you cloned this repo directly, run the following command:

`git pull origin master`

If you forked this repo and then cloned the forked one, run the following commands:

` git remote add upstrean https://github.com/fafranco82/swdestinydb`
`git pull upstream master`

**Comment by w1nterl0ng** [comment]
yes, I initially did a clean pull this morning from github, just did a new pull.. Still having an issue.  I wonder if others can recreate.  I will try with a different deck.

**Comment by fafranco82** [comment]
In my local repo works perfectly. Maybe is a cache issue, try to clear it using one (or both) of these methods:

* run `php app/console cache:clear`
* delete folder `app/cache/dev`

**Comment by w1nterl0ng** [comment]
I would assume it is an issue on my end in one way or another. I have cleared the cache, I have also done a completely clean install and test.  I would be interested to know if others have experienced the same issue or not.
