### ISSUE TITLE
Card List -> Awakenings: "Imperial Armory" Listed Twice

### ISSUE THREAD

**Issue by zliniguez** [fafranco82/swdestinydb#6]
*Summary*
 * In the Awakenings card list the "Imperial Armory" card is listed twice.

*Steps to Reproduce*
 1. Navigate to Awakenings card list (http://swdestinydb.com/set/AW)
 2. Scroll to Battlefield area
 3. Observe that "Imperial Armory" is listed twice

**Comment by fafranco82** [comment]
Fixed.
