### ISSUE TITLE
strip down print view for collections manager

### ISSUE THREAD

**Issue by stopfstedt** [fafranco82/swdestinydb#64]
some ideas for reducing the size of printouts.

![selection_100](https://cloud.githubusercontent.com/assets/1410427/21416166/75405642-c7c5-11e6-8050-a9e2ca63d2ec.png)

- drop the filters. they don't show any selected filters, so they're kinda pointless in their current form.
- remove the dice quantity modifiers. no need to have them in a printout.

thanks and cheers!

**Comment by fafranco82** [comment]
Thanks!
