### ISSUE TITLE
Deckbuilder: Points/Cost Column Improperly Sorted

### ISSUE THREAD

**Issue by zliniguez** [fafranco82/swdestinydb#7]
_Summary_
- The Points/Cost column is sorted as if it was a string, rather than numerically.

_Expected Outcome_
- The column is sorted numerically, so that values such as "10/14" appear after single-digit values.

_Steps to Reproduce_
1. Navigate to Deckbuilder
2. Click "P./C." column header
3. Observe that items are not sorted numerically

![swdestiny-collection-pcsort](https://cloud.githubusercontent.com/assets/1779180/19536497/cc24f084-9611-11e6-9b04-a864a66ac6e5.png)

_Prereqs_
- User is logged in and has items in collection

**Comment by stopfstedt** [comment]
From what I can tell, this would require breaking up the "Points" attribute into two (e.g. Points1 and Points2). AFAIK, ForerunnerDB does not allow the definition of custom, field-specific sorting algorithms, so it will sort points always alphanumerically, rather than numerically.

**Comment by stopfstedt** [comment]
the same applies to the data grid in the collection manager.
