### ISSUE TITLE
Bug: Never get confirmation e-mail

### ISSUE THREAD

**Issue by Keldann** [fafranco82/swdestinydb#71]
Hi, i´m never get to confirm my e-mail.

Can´t login because account is disable, tryed many times re-send the e-mail and doesn´t work.

Not in spam too.

**Comment by fafranco82** [comment]
What is your username?

**Comment by Keldann** [comment]
Keldan

**Comment by fafranco82** [comment]
Your account is now enabled.

Have fun!

**Comment by Keldann** [comment]
Thanks!

**Comment by nschuman027** [comment]
Hi, i'm having the same issue. Just created a new account and didn't receive the confirmation email to activate my account.

Thanks

**Comment by fafranco82** [comment]
@nschuman027 account activated ;)
