### ISSUE TITLE
General Veers - Awakening #4

### ISSUE THREAD

**Issue by cbolinger** [fafranco82/swdestinydb#8]
General Veers is listed as AW# 3 instead of AW#4.

Also typos in the Action description: "this" instead of "thsi"

I assume you already know about the Google Doc with all the cards that have been spoiled:

https://docs.google.com/spreadsheets/d/1nZcJsdL6wY4nWBtzAThpHDKEhpk676azduC5h5RtTU0/edit?usp=sharing

Also, have you considered having moderators to help upload content (images, descriptions etc)? I assume it will be very busy on release day.

Thanks,
Clinton

**Comment by fafranco82** [comment]
Position and typos fixed.

I know the document but it has a lot of partial info. I only add a card when I have full info, and tracking when a line in the doc has the full info in a document I can't edit is awful. So I started to add cards from spoiled images.

The card data will be in [this project](https://github.com/fafranco82/swdestinydb-json-data), but I need first to do some autovalidation work. When that job is done, a helping hand will be very appreciated.
