### ISSUE TITLE
Account on SWdestiny DB is "disabled"

### ISSUE THREAD

**Issue by Jaradrim** [fafranco82/swdestinydb#82]
Hi! I created my account on SWDestiny DB yesterday, but until today I haven't received the confirmation email, so my account is "disabled". 

**User:** Jaradrim
**Email:** jaratorotomas@gmail.com

Hope you can help me!

Best,

**Comment by Jedi-Dreamer** [comment]
Same issue.

Username is: Jedi Dreamer

**Comment by fafranco82** [comment]
Both accounts have benn activated!

Have fun!

**Comment by Jaradrim** [comment]
Thank you!
