### ISSUE TITLE
Bug on validation email

### ISSUE THREAD

**Issue by fpfavero** [fafranco82/swdestinydb#84]
I'm trying to register, but the validation email does not come. I've already checked for spam and archived folders. I also tried registering with different emails in email providers (gmail and yahoo).

**Comment by fafranco82** [comment]
what is your username?

**Comment by fpfavero** [comment]
fpfavero

**Comment by fafranco82** [comment]
Account activated.

**Comment by fpfavero** [comment]
Thanks! Could you activate my friend's account as well? His login is leandroangelo

Thanks again

**Comment by fafranco82** [comment]
Activated, too ;)

**Comment by fpfavero** [comment]
Thanks a lot! =)
