### ISSUE TITLE
Account Creation - Haven't received email for activation, and "resend" button isn't working

### ISSUE THREAD

**Issue by NutellaGrande** [fafranco82/swdestinydb#89]
Hi,

Tried to register an account yesterday (username: Catscratch) and I never received the activation email.  Tried to resend but that button doesn't appear to be doing anything.  I tried again today with a different email address, and everything went smoothly.

Sorry I couldn't reproduce the error, but i'd love to have my original account activated!

**Comment by fafranco82** [comment]
Catscratch account activated.

Have fun!
