### ISSUE TITLE
Some cards are missing their text in the database

### ISSUE THREAD

**Issue by wynalazca** [fafranco82/swdestinydb#9]
List of the cards I found:

http://swdestinydb.com/card/01015
http://swdestinydb.com/card/01026
http://swdestinydb.com/card/01027

These cards maybe just have no text on them, but I can't find images to confirm:
http://swdestinydb.com/card/01034
http://swdestinydb.com/card/01047
http://swdestinydb.com/card/01054

**Comment by fafranco82** [comment]
Fixed.

About the lat three cards, they has no text. But some of them has its flavor text missed... so I fixed them, too.

Thanks for the notice.
