### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Psycho13CZE** [fafranco82/swdestinydb#91]
Hello, sorry for my english skills but a few day ago i register on swdestinyDB, but verification email dont come. I try Click on "Never got the registration email? Click here " but email still dont come. I try register on another my email adress, but problem still persist... Can somebody please help me? Thx

**Comment by fafranco82** [comment]
What is your username?

**Comment by Psycho13CZE** [comment]
"Psycho"
and email ending ..........inek@gmail.com

**Comment by fafranco82** [comment]
Account activated ;)

Have fun!

**Comment by Psycho13CZE** [comment]
Thanks Mate, now everything works fine!
Really thx for your support and help!
