### ISSUE TITLE
Speeder Bike Scout Not Appearing

### ISSUE THREAD

**Issue by StoneTownLegacy** [fafranco82/swdestinydb#96]
When trying to build a hero deck that allows Villain Vehicles (with Finn), Speeder Bike Scout doesn't appear for selection.  Other Villain cards appear, just not this one.  I do have 2 of card and dice in my collection.

**Comment by fafranco82** [comment]
Yes. It's right. The speeder is gray. Finn's ability only allows you to include RED villain vehicles.

**Comment by StoneTownLegacy** [comment]
Good call, sorry about that.  Thanks!
